package:
  name: decoypyrat
  version: "1.0.0"

source:
  url: https://pypi.python.org/packages/0a/85/730b460d84c816e66ab98727cbba960ca4c1ea9cd86cf2a4504013620020/csb-1.2.5.zip
  md5: 06a81ebee65994743ea751819a71620a

build:
    number: 1
    entry_points:
        - decoypyrat = decoypyrat.decoyPYrat:main

requirements:
  build:
    - python
    - setuptools
    - argparse

  run:
    - python
    - argparse

test:
  imports:
    - decoypyrat

about:
  home: https://github.com/tdido/DecoyPYrat
  license: MIT License
  summary: 'Fast Hybrid Decoy Sequence Database Creation for Proteomic Mass Spectrometery Analyses'
