package:
  name: decoypyratplus
  version: "2.0.1"

# source:
#   url: https://pypi.python.org/packages/0a/85/730b460d84c816e66ab98727cbba960ca4c1ea9cd86cf2a4504013620020/csb-1.2.5.zip
#   md5: 06a81ebee65994743ea751819a71620a

build:
    number: 1
    entry_points:
        - decoypyratplus = decoypyrat.decoyPYratPlus:main

requirements:
  build:
    - python
    - setuptools
    - argparse

  run:
    - python
    - argparse

test:
  imports:
    - decoypyrat

about:
  home: https://github.com/ATPs/DecoyPYratPlus
  license: MIT License
  summary: 'Fast Hybrid Decoy Sequence Database Creation for Proteomic Mass Spectrometery Analyses'
